// Code generated by goctl. DO NOT EDIT.
package types

type Meta struct {
	Status int32  `json:"status,default=200"`
	Msg    string `json:"msg,default=succeed"`
}

type Article struct {
	Title       string `json:"title"`
	ParticleId  int64  `json:"particleId"`
	ImageURL    string `json:"imageURL"`
	Desc        string `json:"desc"`
	PublishTime string `json:"publishTime"`
	UpdateTime  string `json:"updateTime"`
}

type GetArticleListResp struct {
	Data []*Article `json:"data"`
	Meta Meta       `json:"meta"`
}

type GetArticlePathReq struct {
	ParticleId int64 `path:"particleId"`
}

type GetArticlePathResp struct {
	Data string `json:"data"`
	Meta Meta   `json:"meta"`
}
